App\Entity\Chapter:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 3
                minMessage: 'Your title must be at least {{ limit }} characters long'
            - App\Validator\Constraints\FirstLetterUppercase: ~